library Update_SDKCheck;

{ 

This is a plugin generated by the PluginHelper 
application. It serves as a starting point for developing plugins
for FMF Dialogue Tool.

Plugin Name: Check for plugin SDK updates 
Author: Dj Unique

Description:

This plugin checks for updates to the plugin SDK.

}

uses
  SysUtils,
  Classes,
  pluginfunc,
  Inifiles,
  dialogs,
  updunit in 'updunit.pas' {DataModule1: TDataModule},
  updform in 'updform.pas' {Form1};


{$R *.res}

function GetPluginName: ShortString; stdcall;
begin;
result := 'Check for plugin SDK updates';
end;
function GetPluginDescription: ShortString; stdcall;
begin;
result := 'checks for plugin sdk updates';
end;
function CanAddToMenu: boolean; stdcall;
begin;
result := True;
end;
procedure RunPlugin (basepath: shortstring); stdcall;
begin;
//MessageDlg('This is supposed to update the SDK. At '+basepath, mtWarning, [mbOK], 0);
datamodule1 := TDataModule1.Create(nil);
cfg := TInifile.create(basepath+'\plugins\sdkinfo.ini');
datamodule1.mxWebUpdate1.ProductInfo.Version := cfg.ReadString('SDK Version Information','CurrentVersion','1.00');

Form1 := TForm1.create(nil);
form1.status.Caption := 'Retrieving update info.';
thepath := basepath;
form1.showmodal;
form1.free;
datamodule1.free;
end;

exports
   GetPluginName,
   GetPluginDescription,
   CanAddToMenu,
   RunPlugin;

begin

end.
